DjangoProject/DjangoProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'polls/',include('polls.urls',namespace='polls')),
    url(r'^admin/', include(admin.site.urls)),
]

DjangoProject/polls/urls.py
#-*- coding:utf-8 -*-

from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^specifics/(?P<question_id>[0-9]+)/$',views.detail,name='detail'),
    url(r'^(?P<question_id>[0-9]+)/result/$',views.results,name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$',views.votes,name='vote'),
]

DjangoProject/polls/models.py
#-*- coding:utf-8 -*-
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

DjangoProject/polls/views.py
#-*- coding:utf-8 -*-

from django.shortcuts import get_object_or_404
from django.http import Http404
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext,loader

from .models import Question,Choice

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = RequestContext(request,{
        'latest_question_list':latest_question_list,
    })
    return render(request,'polls/index.html',context)

def detail(request,question_id):
    try:
        question = Question.objects.get(pk =question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request,'polls/detail.html',{'question':question})
def results(request,question_id):
    result = get_object_or_404(Question,pk = question_id)
    return HttpResponse("you are looking at the results of question %s"%question_id)
def votes(request,question_id):
    return HttpResponse("you are looking at the votes of question %s"%question_id)

DjangoProject/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
    {% endfor %}
<input type="submit" value="Vote"/>
</form>

DjangoProject/polls/templates/polls/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

DjangoProject/polls/templates/polls/result.html
{{ question }}